apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: first-pvc
spec:
  resources:
    requests:
      storage: 1Gi

  selector:
    matchLabels:
      type: local

  accessModes:
    - "ReadWriteOnce"

